In [1]:
import numpy as np

In [2]:
my_sec_list = [1,2,3,4]

In [4]:
myArry = np.array(my_sec_list)

In [5]:
print(myArry)

[1 2 3 4]


In [6]:
2 * myArry

array([2, 4, 6, 8])

In [7]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

In [10]:
np.arange

## Working with Vector

In [12]:
print(type(myArry))

<class 'numpy.ndarray'>


In [15]:
#extract value from array

myArry[-1]

4

In [18]:
#Setting new values
myArry[1]= 10
myArry

array([10, 10,  3,  4])

In [22]:
#Creating vectors with np.arange
SQt = np.arange(17, 23,2.5)
SQt

array([17. , 19.5, 22. ])

## Basic Operations

In [28]:
First = np.arange(1,10)
Sec = np.arange(11,20)

print(First)
print(Sec)


[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


In [32]:
#add 
add = First + Sec

#sub
sub = First - Sec

#mul 
mul = First * Sec

#div
div = First / Sec
rdiv = np.around(First / Sec)
print(add)
print(sub)
print(mul)
print(div)
print(rdiv)

[12 14 16 18 20 22 24 26 28]
[-10 -10 -10 -10 -10 -10 -10 -10 -10]
[ 11  24  39  56  75  96 119 144 171]
[0.09090909 0.16666667 0.23076923 0.28571429 0.33333333 0.375
 0.41176471 0.44444444 0.47368421]
[0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Numpy Datatype

In [37]:
arr = np.arange(0.1,6)
arr
print(arr.dtype)

float64


# Slicing


In [39]:
arr = np.arange(1,20)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [41]:
arr[:2]

array([1, 2])

In [42]:
arr[2:10:2]

array([3, 5, 7, 9])

## Sorting

In [47]:
array = np.array([4,5,6,12,54,9])
array

array([ 4,  5,  6, 12, 54,  9])

In [48]:
#in line sort
array.sort()

In [49]:
array

array([ 4,  5,  6,  9, 12, 54])

In [51]:
array = np.array([4,5,6,12,54,9])
array

array([ 4,  5,  6, 12, 54,  9])

In [54]:
sortedArray = np.sort(array, kind = "merge" )

In [55]:
sortedArray

array([ 4,  5,  6,  9, 12, 54])